apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: insurance
  namespace: argocd
spec:
  project: default

  destination:
    namespace: insurance-sandbox
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/Princecp/insurance-sandbox.git
    path: k8s
    targetRevision: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: true